files:
  - source: /common/src/main/resources/lang/en.json
    translation: /common/src/main/resources/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        bg: bg
        de: de
        es-ES: es
        fr: fr
        nl: nl
        no: no
        pl: pl
        pt-PT: pt
        ru: ru
        tr: tr
        vi: vi
        zh-CN: zh_CN
        zh-HK: zh_HK
